---
- name: Apply underlay configletrs
  hosts: cvaas

  vars_files:
    - ../vars/CVP_Model.yml
    
  tasks:
    - name: Apply underlay configlets
      arista.cvp.cv_device_v3:
        devices: "{{ cvaas_baseline }}"
